server {
    listen 8000 default_server;
    listen [::]:8000 default_server;
    server_name localhost;

    # Sintonía de raíz obligatoria para Laravel
    root /var/www/public;
    index index.php index.html;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Permitir la lectura de enlaces simbólicos para almacenamiento público
    disable_symlinks off;

    # Configuración de subidas (Evita errores de imágenes pesadas)
    client_max_body_size 100M;

    # Rutas de Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesamiento de PHP mediante el Socket FPM
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Assets con caché (Sintonizado para Spatie Media Library y conversiones on-the-fly)
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|webp)$ {
        expires 7d;
        add_header Cache-Control "public";
        log_not_found off;
        access_log off;

        # Si Nginx no encuentra físicamente el archivo large.webp, le pasa la posta a Laravel
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bloquear archivos y carpetas sensibles del sistema interno (Protección Real)
    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~ /(vendor|node_modules|bootstrap/cache|storage/framework|storage/logs|\.env|git) {
        deny all;
        return 404;
    }
}
